/* empty css                      */import{a as y,S as p,i as g}from"./assets/vendor-pJyzcLlr.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();const h="46483266-76bdcaf2ff3adfe100a8b1f15",E="https://pixabay.com/api/",L=15;async function w(e,o=1){const s=`${E}?key=${h}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${L}`;try{return(await y.get(s)).data}catch(r){throw r}}function b(e){const o=document.getElementById("gallery"),s=e.map(r=>`
        <a href="${r.largeImageURL}" class="gallery-item">
            <img src="${r.webformatURL}" alt="${r.tags}">
            <div class="info">
                <p>Likes: ${r.likes}</p>
                <p>Views: ${r.views}</p>
                <p>Comments: ${r.comments}</p>
                <p>Downloads: ${r.downloads}</p>
            </div>
        </a>
    `).join("");o.insertAdjacentHTML("beforeend",s),new p(".gallery a").refresh()}function a(e){g.error({title:"Error",message:e})}function I(){document.getElementById("loader").style.display="block"}function f(){document.getElementById("loader").style.display="none"}function d(e){const o=document.getElementById("load-more");e?o.style.display="block":o.style.display="none"}function B(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}let u="",l=1,c=0;document.getElementById("search-form").addEventListener("submit",async e=>{if(e.preventDefault(),u=document.getElementById("search-input").value.trim(),!u){a("Please enter a search term");return}$(),l=1,await m()});document.getElementById("load-more").addEventListener("click",async()=>{l+=1,await m()});async function m(){I();try{const{hits:e,totalHits:o}=await w(u,l);if(f(),c=o,e.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}b(e),d(c>document.querySelectorAll(".gallery-item").length),l>1&&B(),c<=document.querySelectorAll(".gallery-item").length&&(d(!1),a("We're sorry, but you've reached the end of search results."))}catch{f(),a("Failed to fetch images. Please try again later.")}}function $(){document.getElementById("gallery").innerHTML="",d(!1)}
//# sourceMappingURL=index.js.map
